-- Add new Patreon tiers to LicenseTier enum
ALTER TYPE "LicenseTier" ADD VALUE IF NOT EXISTS 'PATREON_SUPPORTER';
ALTER TYPE "LicenseTier" ADD VALUE IF NOT EXISTS 'PATREON_PLUS';
ALTER TYPE "LicenseTier" ADD VALUE IF NOT EXISTS 'PATREON_PRO';
ALTER TYPE "LicenseTier" ADD VALUE IF NOT EXISTS 'PATREON_ULTIMATE';
