module.exports = {
  apps: [
    {
      name: 'license-api',
      script: 'dist/apps/license-api/main.js',
      cwd: '/app/bitbonsai',
      instances: 2,
      exec_mode: 'cluster',
      env_file: '.env',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/license-api-error.log',
      out_file: './logs/license-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: 'admin-dashboard',
      script: 'serve',
      args: '-s dist/apps/admin-dashboard/browser -l 4200',
      cwd: '/app/bitbonsai',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/admin-dashboard-error.log',
      out_file: './logs/admin-dashboard-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '200M',
    },
    {
      name: 'website',
      script: 'serve',
      args: '-s dist/apps/website/browser -l 4201',
      cwd: '/app/bitbonsai',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/website-error.log',
      out_file: './logs/website-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '200M',
    },
  ],
};
