export enum JobStatus {
  DETECTED = 'DETECTED',
  HEALTH_CHECK = 'HEALTH_CHECK',
  QUEUED = 'QUEUED',
  ENCODING = 'ENCODING',
  VERIFYING = 'VERIFYING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
