#!/bin/sh

# Ensure backend builds succeed
echo "Building backend..."
npx nx build backend

# Ensure frontend builds succeed
echo "Building frontend..."
npx nx build frontend

# Run all tests (unit + integration + coverage)
echo "Running all tests with coverage..."
npx nx test:all

